### ISSUE TITLE
Erreur GuzzleHttp lorsqu'un objet n'existe pas

### ISSUE THREAD

**Issue by raphaelriehl** [apidae-tourisme/apidae-php#16]
Bonjour,

je viens de constater que lorsqu'un objet n'existe pas, cela engendre l'erreur suivante:
> Type error: Argument 1 passed to Sitra\ApiClient\Exception\SitraException::__construct() must be an instance of GuzzleHttp\Exception\RequestException, instance of GuzzleHttp\Command\Exception\CommandClientException given, called in /var/www/cabacms-2-dev/vendor/sitra-tourisme/sitra-api-php/src/Sitra/ApiClient/Client.php on line 289

Mon appel se fait de la manière suivante:
```php
$object = $client->getObjectById([
    'id' => MON_ID,
    ...
]);
```

Je n'ai pas poussé les tests afin de déterminer d'où cela pouvait venir. À priori ces erreurs sont présentes depuis 6 mois déjà.
Pour précision, je suis sur la dernière version de sitra-api-php.

Si quelqu'un a une piste je suis preneur.

Merci d'avance.

**Comment by ghost** [comment]
Bonjour, vous avez essayer avec un simple try catch autour pour gérer l'erreur ?

**Comment by raphaelriehl** [comment]
Bonjour,
merci de votre retour.
Je n'ai pas pris le temps de résoudre ce problème du côté de mon code, mais le try catch est censé résoudre cela en effet.

Mais je voulais le signaler, parce que je pense que le code basé sur une libraire ne doit pas pallier aux erreurs de cette librairie.
Lorsqu'il n'y a aucun objet le comportement normal serait qu'il y ai un retour de type null ou false ou autre, mais pas que ça génère une erreur 500 entraînant l’arrêt du code sans try catch, non ?
N'hésitez pas à me corriger si je me trompe.

**Comment by ghost** [comment]
Ah on est bien d'accord :)
Malheureusement cette classe manque un peu de suivi... ceci dit n'hésitez pas à intervenir dessus et à proposer vos modifications directement sur ce dépôt, c'est fait pour.

Bonne journée

**Comment by raphaelriehl** [comment]
Ça marche. Ce n'est pas une priorité pour l'instant mais je vais me noter ça dans un coin et voir ce que je peux faire.

Bonne journée à vous aussi. :)

**Comment by PierreGranger** [comment]
Bonjour,

La gestion de l'erreur a été corrigée l'implémentation de la pull request https://github.com/apidae-tourisme/sitra-api-php/pull/17
