### ISSUE TITLE
Il manque guzzlehttp/uri-template dans le composer 

### ISSUE THREAD

**Issue by Aurel4012** [apidae-tourisme/apidae-php#20]
Pour info après installation et test de sitra-api-php/examples/demo.php j'ai cette erreur "Fatal error: Uncaught Error: Class 'GuzzleHttp\UriTemplate\UriTemplate' not found"

Résolu avec composer require guzzlehttp/uri-template

**Comment by PierreGranger** [comment]
Bonjour,

J'ai essayé de repartir d'une installation fraîche pour constater le bug mais en ai eu un autre à cause d'une montée en version de guzzlehttp (Uri::resolve deprecated).

J'ai remplace le Uri::resolve par UriResolver::resolve : sur une installation fraîche (composer.lock compris) tout semble rentré dans l'ordre : 
https://github.com/apidae-tourisme/sitra-api-php/commit/1a979c762314d429a6bbb8d5d0b2ef83e2fcda4f

N'hésitez pas cependant à rouvrir cet issue si besoin.

Attention la version sitra-api-php publiée sur packagist n'est pas à jour par rapport au dépôt actuel (il nous manque encore quelques passes de relectures suite à des conflits de montée en version de Guzzle).
