### ISSUE TITLE
Problème sur les dépendances

### ISSUE THREAD

**Issue by fred2nice** [apidae-tourisme/apidae-php#21]
Bonjour,

L'installation par défaut installe guzzlehttp v7, a priori ce n'est pas compatible.
Pour faire fonctionner j'ai downgradé :
{
    "require": {
        "guzzlehttp/uri-template": "^0.2.0",
        "guzzlehttp/guzzle": "^6.0",
        "guzzlehttp/guzzle-services": "^1.1",
        "sitra-tourisme/sitra-api-php": "^1.0"
    }
}

**Comment by gliautard** [comment]
Bonjour,

Je confirme il y à bien un souci si on est trop à jour...

**Comment by PierreGranger** [comment]
Bonjour, une mise à jour de la librairie est prête et remet au propre les dépendances en mettant à jour les composants au passage.
Elle n'est pas encore publiée parce qu'encore en test mais vous pouvez utiliser la branche dev en attendant :

`composer require apidae-tourisme/apidae-php dev:dev`

**Comment by PierreGranger** [comment]
La v2.0.0 a été publiée et devrait régler ces problèmes de dépendances.
