### ISSUE TITLE
Inconsistance au niveau du format de l'API

### ISSUE THREAD

**Issue by jfradj** [apidae-tourisme/apidae-php#31]
Bonjour,

Je remarque des inconsistances au niveau de format de l'API.
Où puis-je vous remonter cela ?
Dans des issues Github ici ?

Cordialement, Johann Fradj

**Comment by PierreGranger** [comment]
Bonjour,

Oui le plus simple est de les remonter ici, je ferai la passerelle si elles ne sont pas liées à la bibliothèque PHP mais plutôt à l'API (si vous êtes sûr que ce n'est pas un problème côté php, vous pouvez aussi créer directement un ticket en envoyant un mail sur hotline.dev@apidae-tourisme.com).

**Comment by jfradj** [comment]
J'ai arrêté de travaillé avec la librairie PHP au bout de quelques heures.
J'ai enchainé plusieurs bugs et j'ai préféré ne pas perdre plus de temps.
Je passe maintenant par les exports et ne suis donc plus confronté qu'au format de l'API.

Toutes les clés sont en français, choix peu usuel mais soit !
Pour autant, je tombe sur un clé nommée en anglais "coordinates"...
Aussi, cette clé référence un tableau (et non une map) où la première valeur (index 0 donc) est la longitude !
C'est assez surprenant d'une part de ne pas avoir des clés nommées, et d'autre part, d'avoir la longitude d'abord...
A-t-on la certitude que les index sont fixes ?

**Comment by PierreGranger** [comment]
Sans rentrer dans le détail, Apidae est une machine d'un certain âge, comme les API V2 qui vont avec : son cycle de vie n'a pas toujours été limpide, alors oui au fil des années il y a clairement eu des choix inconsistants.

Pour autant les API sont fiables et utilisées par plusieurs milliers de projets chaque jour, certains tournant depuis plusieurs années. Si les formats peuvent être déroutants pour les raisons évoquées ci-dessus, ils ont au moins le mérite d'être fiables et constants : toute modification qu'on envisage côté API est toujours accompagnée d'une rétrocompatibilité, ou d'un temps de dépréciation si nécessaire, puisque nous avons énormément dépendances (sites web, applis...) dessus.

Vous trouverez la documentation sur les différents formats sur la documentation officielle :
https://dev.apidae-tourisme.com/documentation-technique/v2/api-de-diffusion/format-des-recherches/

Donc pour répondre à votre question : oui, les index des coordonnées sont fiables, n'ont pas bougé depuis 10 ans, et ne bougeront pas.
