### ISSUE TITLE
Incohérence des données de l'API

### ISSUE THREAD

**Issue by jfradj** [apidae-tourisme/apidae-php#32]
Bonjour,

Je suis tombé sur l'objet #6887164, pour lequel le champ `periodeEnClair` indique :

> Samedi 11 mai 2024 de 10h à 12h.
> Rose de Mai.
> 
> Samedi 22 juin 2024 de 10h à 12h.
> Lavande.
> 
> Samedi 17 août 2024 de 10h à 12h.
> Tubéreuse.
> 
> Samedi 7 septembre 2024 de 10h à 12h.
> Ciste.

Soit 4 jours distincts d'ouverture, alors que le champ `datesOuverture` n'en référence que deux : `["2024-08-17","2024-09-07"]`

```
{
   "periodeEnClair":{
      "libelleFr":"Samedi 11 mai 2024 de 10h \u00e0 12h.\nRose de Mai.\n\nSamedi 22 juin 2024 de 10h \u00e0 12h.\nLavande.\n\nSamedi 17 ao\u00fbt 2024 de 10h \u00e0 12h.\nTub\u00e9reuse.\n\nSamedi 7 septembre 2024 de 10h \u00e0 12h.\nCiste."
   },
   "periodeEnClairGenerationMode":"AUTOMATIQUE",
   "indicationsPeriode":[
      {
         "elementReferenceType":"IndicationPeriode",
         "id":418
      },
      {
         "elementReferenceType":"IndicationPeriode",
         "id":436
      }
   ],
   "periodesOuvertures":[
      {
         "identifiant":30888089,
         "dateDebut":"2024-05-11",
         "dateFin":"2024-05-11",
         "complementHoraire":{
            "libelleFr":"Rose de Mai"
         },
         "horaireOuverture":"10:00:00",
         "horaireFermeture":"12:00:00",
         "type":"OUVERTURE_TOUS_LES_JOURS",
         "tousLesAns":false,
         "identifiantTechnique":30888089
      },
      {
         "identifiant":31063526,
         "dateDebut":"2024-06-22",
         "dateFin":"2024-06-22",
         "complementHoraire":{
            "libelleFr":"Lavande"
         },
         "horaireOuverture":"10:00:00",
         "horaireFermeture":"12:00:00",
         "type":"OUVERTURE_TOUS_LES_JOURS",
         "tousLesAns":false,
         "identifiantTechnique":31063526
      },
      {
         "identifiant":31063533,
         "dateDebut":"2024-08-17",
         "dateFin":"2024-08-17",
         "complementHoraire":{
            "libelleFr":"Tub\u00e9reuse"
         },
         "horaireOuverture":"10:00:00",
         "horaireFermeture":"12:00:00",
         "type":"OUVERTURE_TOUS_LES_JOURS",
         "tousLesAns":false,
         "identifiantTechnique":31063533
      },
      {
         "identifiant":31063536,
         "dateDebut":"2024-09-07",
         "dateFin":"2024-09-07",
         "complementHoraire":{
            "libelleFr":"Ciste"
         },
         "horaireOuverture":"10:00:00",
         "horaireFermeture":"12:00:00",
         "type":"OUVERTURE_TOUS_LES_JOURS",
         "tousLesAns":false,
         "identifiantTechnique":31063536
      }
   ]
}
```

**Comment by jfradj** [comment]
J'ai d'abord pensé que seules des dates futures seraient dans le tableau, mais la date du 17 août me pose question puisque l'export a été généré au moins deux semaines plus tard

**Comment by jfradj** [comment]
Par exemple je vois un autre objet (#6382978)
Qui a comme comme valeur pour le champ `periodeEnClair` :

> Jeudi 18 juillet 2024 à 17h.
> Jeudi 25 juillet 2024 à 17h.
> Jeudi 1er août 2024 à 17h.
> Jeudi 8 août 2024 à 17h.
> Jeudi 22 août 2024 à 17h.
> Mardi 22 octobre 2024 à 11h.
> Mardi 29 octobre 2024 à 11h.
> Mardi 31 décembre 2024 à 11h.

et dans le champ `datesOuverture`, 3 valeurs, toutes dans le futures : `["2024-10-22","2024-10-29","2024-12-31"]`

On notera que la date du 22 août n'est pas présente ! Ce qui paraît logique puisqu'antérieure à l'export.

Mais du coup pourquoi sur l'objet #6887164 on voit un 17 août trainer ?

**Comment by PierreGranger** [comment]
Bonjour,

Pour le support sur les API, qui ne concerne donc pas la bibliothèque php ici, je vous invite à passer par l'adresse hotline.dev@apidae-tourisme.com pour créer un ticket. J'ai ouvert un ticket #40199, en reprenant les informations ci-dessus, vous devriez recevoir les réponses par mail.
