### ISSUE TITLE
URL incorrectes dans README.md

### ISSUE THREAD

**Issue by dClauzel** [apidae-tourisme/apidae-php#6]
La documentation fait plusieurs fois référence à des URL comme `http://api.sitra-tourisme.com/` alors qu’elles devraient plutôt être de la forme `https://api.apidae-tourisme.com/`. Je suppose qu’il en va de même pour `http://export.sitra-tourisme.com/` qui serait plutôt `https://export.apidae-tourisme.com/`

D’ailleurs, le certificat TLS pour le domaine `api.sitra-tourisme.com` vient d’expirer.

**Comment by SergeBregliano** [comment]
Bonjour Damien,

Très juste. Beaucoup de modifs avaient été faites dans le core du projet mais la doc, les exemples... Oooops ! Un peu oubliés.
Tout ça vient d'être corrigé dans la dernière version.

Merci beaucoup pour ta vigilance et ton point d'alerte.
Bien cordialement,
Serge
