### ISSUE TITLE
Problème au niveau du stream dans l'export des fichiers

### ISSUE THREAD

**Issue by HackLo** [apidae-tourisme/apidae-php#8]
J'ai un problème au niveau du stream dans le client Sitra\ApiClient\Client, ligne 178. Ma réponse est vide ensuite lors du $response->getBody() pour l'injecter dans le fichier avec file_put_contents.

J'ai 2 idées de solutions : 

1. Pouvoir passer un save_to à la méthode get : $client->get($params['url'], ['save_to' => $zipFullPath]);
2. Changer la visibilité des fonctions private en protected pour permettre d'étendre la classe en changeant juste la fonction getExportFiles.

**Comment by lalmeras** [comment]
Comment déterminez-vous que $response->getBody() est vide ? Attention cette variable est un stream (https://stackoverflow.com/questions/44593272/guzzle-returns-stream-empty-body-instead-of-json-body)

**Comment by HackLo** [comment]
Effectivement, j'ai été un peu vite dans la description. Lorsque j'utilise la version du dépôt, j'ai en retour un Finder, qui me retourne aucun fichier via la méthode files(). Avec la modification du save_to, j'ai bien des fichiers retournés par le files(). Peut-être qu'il y a une différence qui m'échappe entre les 2 ?

**Comment by lalmeras** [comment]
La version utilisée est-elle la version du dépôt git ou la version publiée sur https://packagist.org/packages/sitra-tourisme/sitra-api-php

Si c'est la version du dépôt git, je pense que l'update de la version de guzzle-services vers dev-develop pose souci.

Avec l'aide de ce code simple, il est possible de reproduire le problème (pas de réponse), ainsi que de déterminer que la dernière version qui permettent de récupérer le contenu attendu est la 0.6.0 :

``` php
<?php

require 'vendor/autoload.php';
use GuzzleHttp\Command\Guzzle\GuzzleClient;
use GuzzleHttp\Command\Guzzle\Description;
use GuzzleHttp\Client;

$descriptionData = [
];

$client = new GuzzleClient(new Client([]), new Description($descriptionData));

$response = $client->getHttpClient()->get('https://httpbin.org/', ['stream' => true]);
print (string) $response->getBody();

?>
```

@olivierdepriester 
Il faut donc faire un revert sur cet update de la mise à jour guzzle https://github.com/apidae-tourisme/sitra-api-php/commit/30a472c3b592b324eb4fc6b5fb0ba7f1954dbc80 ou utiliser la version 0.6.0

A noter qu'il existe aussi une PR#7 et un dépôt https://github.com/2ndGAB/Apidae_api_php7/ proposant une version avec un guzzle plus récent.

**Comment by ghost** [comment]
Bonjour à tous les deux,

J'ai peut-être mal compris mais je n'arrive pas à reproduire votre bug.
Si j'ai bien compris ça se passe à la ligne https://github.com/apidae-tourisme/sitra-api-php/blob/master/src/Sitra/ApiClient/Client.php#L188

Donc dans https://github.com/apidae-tourisme/sitra-api-php/blob/master/src/Sitra/ApiClient/Client.php#L164 ?

J'ai essayé de reproduire comme suit : 
```
    ini_set('display_errors',1) ;
    error_reporting(E_ALL) ;

    require __DIR__."/../../../autoload.php";
    require __DIR__."/../config.inc.php";

    $client = new \Sitra\ApiClient\Client($config) ;

    $exportFiles = $client->getExportFiles([
        'url' => $url_test_zip
    ]);
```
J'ai bien un extract complet dans le dossier souhaité : est-ce que c'est bien là qu'est sensé se situer le problème ?

Un bug a récemment été corrigé concernant l'utilisation de Guzzle et notamment de guzzle-service, mais à priori ce n'est pas lié. Pouvez-vous me confirmer si ça fonctionne pour vous avec la version actuellement en production ?
https://github.com/apidae-tourisme/sitra-api-php/commit/90dc7bd13ec1b435a73c8da67b55857e2af24bf5
